modLoader="javafml"
loaderVersion="[43,)"
license="(c) 2023-2026 LDM. All rights reserved."

[[mods]]
modId="mo_potions"
version="1.5.2+1.19.2"
displayName="Mo' Potions"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-potions"
logoFile="logo.png"
authors="LDM"
description='''
Adds more potions to Minecraft! You can now brew almost anything, from Haste to Blindness!
'''

[[dependencies.mo_potions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




